[package]
name = "bb-flasher-mspm0"
version = "0.1.0"
description = "A library to flash the MSPM0 co-processor over its UART/I2C bootloader (BSL)"
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
readme = "README.md"
keywords = ["mspm0", "bsl", "flasher", "beagle"]
categories = ["embedded", "hardware-support"]

[dependencies]
serialport = { version = "4.7", default-features = false, optional = true }
thiserror = "2.0"
tracing = "0.1"
zerocopy = { version = "0.8", features = ["std", "derive"] }
bin_file = "0.2"
crc-fast = "1.10"
bb-helper = { version = "0.1", path = "../bb-helper", features = ["cancel"] }

[target.'cfg(target_os = "linux")'.dependencies]
i2cdev = { version = "0.6", optional = true }
gpiocdev = "0.8"
nix = { version = "0.31", features = ["fs"], optional = true }

[features]
# Since uart is cross-platform, can be enabled by default.
default = ["uart"]
uart = ["serialport"]
i2c = ["i2cdev", "nix"]

[package.metadata.docs.rs]
all-features = true
