[package]
name = "bb-imager-ui"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
iced = { version = "0.14", features = ["tokio"] }
bb-iced-widgets = { path = "../bb-iced-widgets" }
url = "2.5"
chrono = "0.4"
bb-config = { path = "../bb-config" }
chrono-tz = "0.10"

[dev-dependencies]
tempfile = "3.27"
bb-config = { path = "../bb-config" }
serde_json = { version = "1.0.150" }
tokio = { version = "1.52" }
bb-downloader = { path = "../bb-downloader" }

[features]
debug = ["iced/hot"]
