FROM rust:latest

RUN dpkg --add-architecture armhf
RUN apt-get update \
    && apt-get --assume-yes install desktop-file-utils libssl-dev:armhf libudev-dev:armhf gcc-arm-linux-gnueabihf \
    && rm -rf /var/lib/apt/lists/*

RUN rustup target add armv7-unknown-linux-gnueabihf
RUN cargo install cargo-deb

ENV PKG_CONFIG_PATH="/usr/lib/arm-linux-gnueabihf/pkgconfig/:${PKG_CONFIG_PATH}"
ENV PKG_CONFIG_ALLOW_CROSS=1
ENV CARGO_TARGET_ARMV7_UNKNOWN_LINUX_GNUEABIHF_LINKER=arm-linux-gnueabihf-gcc
