FROM rust:latest

RUN dpkg --add-architecture arm64
RUN apt-get update \
    && apt-get --assume-yes install desktop-file-utils libssl-dev:arm64 libudev-dev:arm64 gcc-aarch64-linux-gnu \
    && rm -rf /var/lib/apt/lists/*

RUN rustup target add aarch64-unknown-linux-gnu
RUN cargo install cargo-deb

ENV PKG_CONFIG_PATH="/usr/lib/aarch64-linux-gnu/pkgconfig/:${PKG_CONFIG_PATH}"
ENV PKG_CONFIG_ALLOW_CROSS=1
ENV CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc
