name: Create Release artifacts

on:
  push:
    branches: [ "main" ]
    tags: [ "[0-9]+.[0-9]+.[0-9]+" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  VERBOSE: 1

defaults:
  run:
    shell: bash

jobs:
  linux:
    strategy:
      matrix:
        platform: [ ubuntu-22.04, ubuntu-22.04-arm ]

    name: Build Artifacts - ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        lfs: true

    - name: Setup deps
      run: make setup-debian-deps

    - name: Select rust toolchain
      run: rustup toolchain install stable --profile minimal

    - name: Set version
      if: github.ref_type == 'tag'
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Set PRE_RELEASE Environment Variable
      if: github.ref_type != 'tag'
      run: echo "PRE_RELEASE=1" >> $GITHUB_ENV

    - name: Use caching
      uses: Swatinem/rust-cache@v2
      with:
        prefix-key: "v1"
        
    - name: Install packaging deps
      run: make setup-packaging-deps

    - name: Build packages
      run: make package-host

    # Build CLI Snap
    - run: ln -sf snapcraft.cli.yaml snapcraft.yaml
    - uses: snapcore/action-build@v1

    # Build GUI Snap
    - run: ln -sf snapcraft.gui.yaml snapcraft.yaml
    - uses: snapcore/action-build@v1

    - run: |
        mv bb-imager-cli_*.snap bb-imager-cli/dist/
        mv bb-imager_*.snap bb-imager-gui/dist/

    # Do not do versioning for Pre-Release packages
    - name: Rename Pre-Release Packages
      if: github.ref_type != 'tag'
      run: make package-rename

    - name: Pre-Release
      uses: softprops/action-gh-release@v3
      if: github.event_name != 'pull_request' && github.ref_type != 'tag'
      with:
        prerelease: true
        name: Continuous Release
        tag_name: continuous-release
        files: |
          bb-imager-gui/dist/*
          bb-imager-cli/dist/*

    - name: Release
      uses: softprops/action-gh-release@v3
      if: github.ref_type == 'tag'
      with:
        generate_release_notes: false
        files: |
          bb-imager-gui/dist/*
          bb-imager-cli/dist/*

    - name: Upload artifacts
      uses: actions/upload-artifact@v7
      if: github.event_name == 'pull_request'
      with:
        name: artifacts-${{ matrix.platform }}
        path: |
          bb-imager-gui/dist/*
          bb-imager-cli/dist/*

  linux-cross:
    name: Build Artifacts - armv7-unknown-linux-gnueabihf
    runs-on: ubuntu-24.04
    env:
      NO_BUILD: 1
    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        lfs: true

    - name: Set version
      if: github.ref_type == 'tag'
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Set PRE_RELEASE Environment Variable
      if: github.ref_type != 'tag'
      run: echo "PRE_RELEASE=1" >> $GITHUB_ENV

    - name: Build binary
      uses: houseabsolute/actions-rust-cross@v1
      with:
        command: build
        target: armv7-unknown-linux-gnueabihf
        args: "--locked --release -F bcf_msp430,bcf_cc1352p7,dfu,zepto_uart,zepto_i2c -p bb-imager-cli"
        strip: true

    - name: Install packaging deps
      run: make setup-packaging-deps

    - name: Build packages
      run: make package-armv7-unknown-linux-gnueabihf

    # Do not do versioning for Pre-Release packages
    - name: Rename Pre-Release Packages
      if: github.ref_type != 'tag'
      run: make package-rename

    - name: Pre-Release
      uses: softprops/action-gh-release@v3
      if: github.event_name != 'pull_request' && github.ref_type != 'tag'
      with:
        prerelease: true
        name: Continuous Release
        tag_name: continuous-release
        files: |
          bb-imager-gui/dist/*
          bb-imager-cli/dist/*

    - name: Release
      uses: softprops/action-gh-release@v3
      if: github.ref_type == 'tag'
      with:
        generate_release_notes: false
        files: |
          bb-imager-gui/dist/*
          bb-imager-cli/dist/*

    - name: Upload artifacts
      uses: actions/upload-artifact@v7
      if: github.event_name == 'pull_request'
      with:
        name: artifacts-armv7-unknown-linux-gnueabihf
        path: |
          bb-imager-gui/dist/*
          bb-imager-cli/dist/*

  vendor-deps:
    name: Vendor dependencies
    runs-on: ubuntu-24.04
    if: github.ref_type == 'tag'
    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        lfs: true

    - name: Create dependency tar
      run: make vendor-deps

    - name: Release
      uses: softprops/action-gh-release@v3
      with:
        generate_release_notes: true
        files: cargo-vendor.tar.gz

  macos-job:
    name: Build MacOS Artifacts
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        lfs: true

    - name: Set version
      if: github.ref_type == 'tag'
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Set PRE_RELEASE Environment Variable
      if: github.ref_type != 'tag'
      run: echo "PRE_RELEASE=1" >> $GITHUB_ENV

    - name: Select rust toolchain
      run: rustup toolchain install stable --profile minimal

    - name: Add Rust targets
      run:  rustup target add aarch64-apple-darwin x86_64-apple-darwin

    - name: Use caching
      uses: Swatinem/rust-cache@v2
      with:
        prefix-key: "v2"
        
    - name: Install packaging deps
      run: make setup-packaging-deps

    # The ENV variable names are what cargo-packager requires
    - name: Setup macos signing
      working-directory: bb-imager-gui
      if: github.event_name != 'pull_request'
      run: |
        echo "" >> Cargo.toml
        echo "[package.metadata.packager.macos]" >> Cargo.toml
        echo "signing_identity = \"${{ secrets.TEAM_ID }}\"" >> Cargo.toml

    - name: Build packages
      env:
        APPLE_CERTIFICATE: ${{ secrets.CERT_DEVELOPER_APP_BASE64 }}
        APPLE_CERTIFICATE_PASSWORD: ${{ secrets.CERT_PASSWORD }}
        APPLE_ID: ${{ secrets.APPLE_ID }}
        APPLE_PASSWORD: ${{ secrets.APP_PASSWORD }}
        APPLE_TEAM_ID: ${{ secrets.TEAM_ID }}
      run: make package-x86_64-apple-darwin package-aarch64-apple-darwin

    # Do not do versioning for Pre-Release packages
    - name: Rename Pre-Release Packages
      if: github.ref_type != 'tag'
      run: make package-rename

    - name: Pre-Release
      uses: softprops/action-gh-release@v3
      if: github.event_name != 'pull_request' && github.ref_type != 'tag'
      with:
        prerelease: true
        name: Continuous Release
        tag_name: continuous-release
        files: |
          bb-imager-gui/dist/*

    - name: Release
      uses: softprops/action-gh-release@v3
      if: github.ref_type == 'tag'
      with:
        generate_release_notes: false
        files: |
          bb-imager-gui/dist/*

    - name: Upload artifacts
      uses: actions/upload-artifact@v7
      if: github.event_name == 'pull_request'
      with:
        name: artifacts-macos
        path: |
          bb-imager-gui/dist/*

  windows-job:
    name: Build Windows Artifacts
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        lfs: true

    - name: Set version
      if: github.ref_type == 'tag'
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Set PRE_RELEASE Environment Variable
      if: github.ref_type != 'tag'
      run: echo "PRE_RELEASE=1" >> $GITHUB_ENV

    - name: Select rust toolchain
      run: rustup toolchain install stable --profile minimal

    - name: Add rust target
      run:  rustup target add x86_64-pc-windows-msvc aarch64-pc-windows-msvc

    - name: Use caching
      uses: Swatinem/rust-cache@v2
      with:
        prefix-key: "v1"
        
    - name: Install packaging deps
      run: make setup-packaging-deps

    - name: Build packages
      run: make package-aarch64-pc-windows-msvc package-x86_64-pc-windows-msvc

    # Do not do versioning for Pre-Release packages
    - name: Rename Pre-Release Packages
      if: github.ref_type != 'tag'
      run: make package-rename

    - name: Pre-Release
      uses: softprops/action-gh-release@v3
      if: github.event_name != 'pull_request' && github.ref_type != 'tag'
      with:
        prerelease: true
        name: Continuous Release
        tag_name: continuous-release
        files: |
          bb-imager-gui/dist/*

    - name: Release
      uses: softprops/action-gh-release@v3
      if: github.ref_type == 'tag'
      with:
        generate_release_notes: false
        files: |
          bb-imager-gui/dist/*

    - name: Upload artifacts
      uses: actions/upload-artifact@v7
      if: github.event_name == 'pull_request'
      with:
        name: artifacts-windows
        path: |
          bb-imager-gui/dist/*
